### ISSUE TITLE
Security contact

### ISSUE THREAD

**Issue by lumisota** [BenWiederhake/domain-word#2]
Is there a preferred security contact for this project?

**Comment by BenWiederhake** [comment]
Hi! I don't see how there's anything security-relevant here? You can write it here, or in the worst case if you're really worried we can try to chat somewhere.

**Comment by lumisota** [comment]
Hi Ben; thanks for your reply. The reason for my message is that we're carrying out research to identify the potential impacts of using old versions of the Public Suffix List, and have found that your project uses an out-of-date version of the list (in `src/public_suffix_list.dat`).

The Public Suffix List is regularly updated (generally a few times per week), and to ensure that the correct privacy boundaries are maintained between websites, applications that use it should routinely fetch an updated copy. If new suffixes are added to the list, and an old list is then used, privacy boundaries will not be constructed correctly, allowing for data (e.g., cookies) to be set incorrectly, potentially harming privacy.

There is further guidance on how the Public Suffix List should be used in ICANN’s “Advisory on the Use of Static TLD / Suffix Lists” at https://www.icann.org/en/system/files/files/sac-070-en.pdf.

Happy to help if you have any questions about our work; thanks again.

**Comment by BenWiederhake** [comment]
This is a funny side project, written in about ten minutes. If you didn't notice that, then I'm worried about the quality of your research.

Closing, as there is no actual issue.
